BIN := {% raw %}{{ cookiecutter.project_slug }}{% endraw %}

.PHONY: all tidy fmt lint install clean

all: tidy fmt lint build install

tidy:
	go mod tidy

fmt:
	gofumpt -w .

lint:
	golangci-lint run

build: $(BIN)
	go build -o $(BIN) main.go

install: build
	go install

clean:
	$(RM) $(BIN)
